SinExWebApp20328800/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SinExWebApp20328800.Models
{
    [Table("Payment")]
    public class Payment
    {
        [Key]
        [Required]
        public virtual int PaymentID { get; set; }
        [Required]
        public virtual string AuthorizationCode { get; set; }
        [Required]
        public virtual int WaybillID { get; set; }
        public virtual decimal PaymentAmount { get; set; }
        public virtual string CurrencyCode { get; set; }
        public virtual string UserName { get; set; }
        public virtual string PayerCharacter { get; set; }
        public virtual string PaymentDescription { get; set; }

        [ForeignKey("WaybillID")]
        public virtual Shipment Shipment { get; set; }

    }
}

SinExWebApp20328800/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SinExWebApp20328800.Models;
using SinExWebApp20328800.ViewModels;
using X.PagedList;

namespace SinExWebApp20328800.Controllers
{
    public class PaymentsController : Controller
    {
        private SinExWebApp20328800DatabaseContext db = new SinExWebApp20328800DatabaseContext();

        private ShippingAccount GetCurrentAccount()
        {
            string username = System.Web.HttpContext.Current.User.Identity.Name;
            if (username == null)
            {
                return null;
            }
            ShippingAccount current_account = db.ShippingAccounts.SingleOrDefault(s => s.UserName == username);
            return current_account;
        }

        private SelectList PopulateShippingAccountsDropdownList()
        {
            // TODO: Construct the LINQ query to retrieve the unique list of shipping account ids.
            var shippingAccountQuery = db.Payments.Select(s => s.UserName).Distinct().OrderBy(s => s);
            var hehe = db.ShippingAccounts.Where(m => shippingAccountQuery.Contains(m.UserName)).Select(m => m.ShippingAccountId).Distinct().OrderBy(m => m);

            return new SelectList(hehe);
        }

        public ActionResult GeneratePaymentHistoryReport(
            int? ShippingAccountId,
            int? WaybillId,
            DateTime? StartingDate,
            DateTime? EndingDate,
            string sortOrder,
            int? currentShippingAccountId,
            int? currentWaybillId,
            DateTime? currentStartingDate,
            DateTime? currentEndingDate,
            int? page)
        {
            // Instantiate an instance of the PaymentsReportViewModel and the PaymentsSearchViewModel.
            var PaymentReport = new PaymentsReportViewModel();
            PaymentReport.PaymentSearch = new PaymentsSearchViewModel();

            // Code for paging.
            ViewBag.CurrentSort = sortOrder;
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            // Retain search conditions for sorting.
            if (StartingDate == null)
            {
                StartingDate = currentStartingDate;
            }
            if (EndingDate == null)
            {
                EndingDate = currentEndingDate;
            }
            if (ShippingAccountId == null)
            {
                ShippingAccountId = currentShippingAccountId;
            }
            if (WaybillId == null)
            {
                WaybillId = currentWaybillId;
            }
            else
            {
                page = 1;
            }
            ViewBag.CurrentShippingAccountId = ShippingAccountId;
            ViewBag.CurrentWaybillId = WaybillId;
            ViewBag.CurrentStartingDate = StartingDate;
            ViewBag.CurrentEndingDate = EndingDate;

            PaymentReport.PaymentSearch.ShippingAccountId = ShippingAccountId == null ? 0 : (int)ShippingAccountId;
            PaymentReport.PaymentSearch.WaybillId = WaybillId == null ? 0 : (int)WaybillId;
            // Populate the ShippingAccountId dropdown list.

            if (User.IsInRole("Employee"))
            {
                var n = PopulateShippingAccountsDropdownList().ToList();
                foreach (SelectListItem k in n)
                {
                    k.Value = k.Text;
                }
                n.Insert(0, new SelectListItem
                {
                    Text = "All",
                    Value = "0"
                });
                int haha = 0;
                for (int i = 0; i < n.Count(); i++)
                {
                    if (n.ElementAt(i).Value == ShippingAccountId.ToString())
                    {
                        haha = i;
                        break;
                    }
                }
                foreach (var item in n)
                {
                    if (item.Value == ShippingAccountId.ToString())
                    {
                        item.Selected = true;
                    }
                }
                PaymentReport.PaymentSearch.ShippingAccounts = n;
                if(!(ShippingAccountId == 0 || ShippingAccountId == null))
                {
                    string accountusername = db.ShippingAccounts.Single(i => i.ShippingAccountId == ShippingAccountId).UserName;
                    PaymentReport.PaymentSearch.WaybillIds = new SelectList(db.Payments.Where(o => o.UserName == accountusername).Select(o => o.WaybillID).Distinct()).ToList();
                }
                else
                {
                    IQueryable<int> foo = Enumerable.Empty<int>().AsQueryable();
                    foo = foo.Concat(new int[] { 0 });
                    PaymentReport.PaymentSearch.WaybillIds = new SelectList(foo).ToList();
                }
            }
            else
            {
                PaymentReport.PaymentSearch.ShippingAccounts = null;
                string accountusername = GetCurrentAccount().UserName;
                PaymentReport.PaymentSearch.WaybillIds = new SelectList(db.Payments.Where(o => o.UserName == accountusername).Select(o => o.WaybillID).Distinct()).ToList();
            }

            //Initialize the query to retrieve payments using the PaymentsListViewModel.
            var list = new List<PaymentsListViewModel>();
            foreach (Payment v in db.Payments)
            {
                PaymentsListViewModel m = new PaymentsListViewModel();
                Shipment ship = db.Shipments.SingleOrDefault(a => a.WaybillId == v.WaybillID);
                m.WaybillId = v.WaybillID;
                m.ShippingAccountId = v.PayerCharacter == "Recipient" ? ship.RecipientShippingAccountID : ship.SenderShippingAccountID;
                m.ShipDate = (DateTime)ship.PickupDate;
                m.RecipientName = ship.RecipientFullName;
                m.OriginCity = ship.Origin;
                m.DestinationCity = ship.Destination;
                m.ServiceType = db.ServiceTypes.Single(a => a.ServiceTypeID == ship.ServiceTypeID).Type;
                m.TotalPaymentAmount = v.PaymentAmount;
                m.PaymentDescription = v.PaymentDescription;
                m.CurrencyCode = v.CurrencyCode;

                ShippingAccount lala_account = db.ShippingAccounts.Single(a => a.UserName == v.UserName);
                Shipment lala_shipment = db.Shipments.Single(a => a.WaybillId == v.WaybillID);
                m.SenderReferenceNumber = lala_shipment.ReferenceNumber;
                m.SenderFullName = "";
                if (lala_shipment.SenderShippingAccount is PersonalShippingAccount)
                {
                    PersonalShippingAccount temp = (PersonalShippingAccount)db.ShippingAccounts.Single(a => a.ShippingAccountId == lala_shipment.SenderShippingAccountID);
                    m.SenderFullName = temp.FirstName + temp.LastName;
                }
                else
                {
                    BusinessShippingAccount temp = (BusinessShippingAccount)db.ShippingAccounts.Single(a => a.ShippingAccountId == lala_shipment.SenderShippingAccountID);
                    m.SenderFullName = temp.ContactPersonName;
                }
                m.SenderMailingAddress = lala_shipment.SenderShippingAccount.ProvinceCode + ", " + lala_shipment.SenderShippingAccount.City + ", " + lala_shipment.SenderShippingAccount.StreetInformation + ", " + lala_shipment.SenderShippingAccount.BuildingInformation;
                m.RecipientFullName = lala_shipment.RecipientFullName;
                m.RecipientDeliveryAddress = lala_shipment.RecipientDeliveryProvince + ", " + lala_shipment.RecipientDeliveryCity + ", " + lala_shipment.RecipientDeliveryStreet + ", " + lala_shipment.RecipientDeliveryBuilding;
                m.CreditCardType = lala_account.Type;
                m.CreditCardNumber = lala_account.Number.Substring(lala_account.Number.Length - 4);
                m.AuthorizationCode = v.AuthorizationCode;

                m.Packages = lala_shipment.Packages;
                list.Add(m);
            }
            var paymentQuery = list.AsQueryable();
            // Add the condition to select a spefic shipping account if shipping account id is not null.

            if (User.IsInRole("Employee"))
            {
                if (ShippingAccountId != 0 && ShippingAccountId != null)
                {
                    paymentQuery = paymentQuery.Where(s => s.ShippingAccountId == ShippingAccountId);
                    if (WaybillId != 0 && WaybillId != null)
                    {
                        paymentQuery = paymentQuery.Where(s => s.WaybillId == WaybillId);
                    }
                }
            }
            else
            {
                int accountid = GetCurrentAccount().ShippingAccountId;
                ViewBag.lala = accountid;
                paymentQuery = paymentQuery.Where(p => p.ShippingAccountId == accountid);
                if (WaybillId != 0 && WaybillId != null)
                {
                    paymentQuery = paymentQuery.Where(s => s.WaybillId == WaybillId);
                }
            }


            if ((StartingDate != null) && (EndingDate != null))
            {
                paymentQuery = paymentQuery.Where(s => (s.ShipDate > StartingDate && s.ShipDate < EndingDate));
            }
            else
            {
                // Return an empty result if no shipping account id has been selected.
                PaymentReport.PaymentList = new PaymentsListViewModel[0].ToPagedList(pageNumber, pageSize);
            }

            // Code for sorting on ServiceType, ShippedDate, DeliveredDate, RecipientName, Origin, Destination
            ViewBag.ServiceTypeSortParm = sortOrder == "serviceType" ? "serviceType_desc" : "serviceType";

SinExWebApp20328800/Views/Payments/Create.cshtml
@model SinExWebApp20328800.Models.Payment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AuthorizationCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorizationCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorizationCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WaybillID, "WaybillID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WaybillID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WaybillID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrencyCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrencyCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrencyCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PayerCharacter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PayerCharacter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PayerCharacter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SinExWebApp20328800/Views/Payments/Delete.cshtml
@model SinExWebApp20328800.Models.Payment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Shipment.ReferenceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shipment.ReferenceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorizationCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorizationCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrencyCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrencyCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayerCharacter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayerCharacter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SinExWebApp20328800/Views/Payments/Details.cshtml
@model SinExWebApp20328800.Models.Payment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Shipment.ReferenceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shipment.ReferenceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorizationCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorizationCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrencyCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrencyCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayerCharacter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayerCharacter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PaymentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SinExWebApp20328800/Views/Payments/Edit.cshtml
@model SinExWebApp20328800.Models.Payment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PaymentID)

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorizationCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorizationCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorizationCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WaybillID, "WaybillID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WaybillID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WaybillID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrencyCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrencyCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrencyCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PayerCharacter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PayerCharacter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PayerCharacter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SinExWebApp20328800/Views/Payments/GeneratePaymentHistoryReport.cshtml
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<link href="~/Content/jquery-ui-timepicker-addon.min.css" rel="stylesheet" />
@model SinExWebApp20328800.ViewModels.PaymentsReportViewModel

@{
    ViewBag.Title = "Invoice History";
}

<h2>Invoice History</h2>
<hr />
@Html.Partial("_PaymentsSearchPartial", Model.PaymentSearch)
@Html.Partial("_PaymentsListPartial", Model.PaymentList)
@Html.Partial("_PaymentsPagingPartial", Model.PaymentList)

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-timepicker-addon.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(function () {
                $(".date-time-picker").datetimepicker({
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-100:+0",
                    dateFormat: 'yy/mm/dd',
                    controlType: 'select',
                    timeFormat: 'HH:mm'
                });
            });

            jQuery.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                if (isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            };
        });
    </script>
}

SinExWebApp20328800/Views/Payments/Index.cshtml
@model IEnumerable<SinExWebApp20328800.Models.Payment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Shipment.ReferenceNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuthorizationCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrencyCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PayerCharacter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentDescription)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Shipment.ReferenceNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AuthorizationCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PaymentAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrencyCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PayerCharacter)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PaymentDescription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PaymentID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PaymentID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PaymentID })
        </td>
    </tr>
}

</table>

SinExWebApp20328800/Views/Payments/_PaymentsPagingPartial.cshtml
@model X.PagedList.IPagedList<SinExWebApp20328800.ViewModels.PaymentsListViewModel>

@using X.PagedList.Mvc

@if (Model.PageCount > 1)
{
    <center>
        <div class="pagination">
            @Html.PagedListPager(Model, page => Url.Action("GeneratePaymentHistoryReport", new
       {
           page,
           sortOrder = ViewBag.CurrentSort,
           currentShippingAccountId = ViewBag.CurrentShippingAccountId,
           currentStartingDate = ViewBag.CurrentStartingDate,
           currentEndingDate = ViewBag.CurrentEndingDate
       }))
            Page @Model.PageNumber of @Model.PageCount
        </div>
    </center>
}

SinExWebApp20328800/Views/Payments/_PaymentsSearchPartial.cshtml
@model SinExWebApp20328800.ViewModels.PaymentsSearchViewModel

@using (Html.BeginForm("GeneratePaymentHistoryReport", "Payments", FormMethod.Get))
{
    <div class="form-group">
        <div class="col-md-12">
            @Html.LabelFor(a => a.ShippingAccountId, "Shipping Account: ")
            @if (User.IsInRole("Employee"))
            {
                @Html.DropDownListFor(a => a.ShippingAccountId, Model.ShippingAccounts, new { @class = "form-control", @Value = ViewBag.CurrentShippingAccountId , onchange = "+onShippingAccountIdChange(this)", id = "s_ddl" })
            }
            else
            {
                @Html.EditorFor(a => a.ShippingAccountId, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.lala, @readonly = "readonly" } })
            }
            @Html.ValidationMessageFor(a => a.ShippingAccountId, "", new { @class = "text-danger" })
        </div>

        <div class="col-md-12">
            @Html.LabelFor(a => a.WaybillId, "Waybill Id: ")
            @Html.DropDownListFor(a => a.WaybillId, Model.WaybillIds, new { @class = "form-control", @Value = ViewBag.CurrentWaybillId == null ? 0: ViewBag.CurrentWaybillId, id = "sizes_ddl" })
            @Html.ValidationMessageFor(a => a.WaybillId, "", new { @class = "text-danger" })
        </div>

        <div class="col-md-12">
            @Html.LabelFor(a => a.StartingDate, "Date from ")
            @Html.EditorFor(a => a.StartingDate, new { htmlAttributes = new { @class = "form-control date-time-picker", @Value = ViewBag.CurrentStartingDate != null ? ViewBag.CurrentStartingDate.ToString("yyyy/MM/dd HH:mm") : DateTime.Now.ToString("yyyy/MM/dd HH:mm") } })
            @Html.ValidationMessageFor(model => model.StartingDate, "", new { @class = "text-danger" })

            @Html.LabelFor(a => a.EndingDate, "To ")
            @Html.EditorFor(a => a.EndingDate, new { htmlAttributes = new { @class = "form-control date-time-picker", @Value = ViewBag.CurrentEndingDate != null ? ViewBag.CurrentEndingDate.ToString("yyyy/MM/dd HH:mm") : DateTime.Now.ToString("yyyy/MM/dd HH:mm") } })
            @Html.ValidationMessageFor(model => model.EndingDate, "", new { @class = "text-danger" })

            <input type="submit" class="btn btn-default" value="Search" />
        </div>
    </div>
}

<script type="text/javascript">
    function AppendUrlParamTokens(url, params) {

        for (var param in params) {
            if (params[param] == null) {
                delete params[param];
            }
        }

        return url + "?" + jQuery.param(params);
    }

    function onShippingAccountIdChange(ddl) {
        jQuery.getJSON(AppendUrlParamTokens('@Url.Action("GetWaybillIds", "Payments")', { shippingaccountid: ddl.options[ddl.selectedIndex].value }), function (result) {
            var target = jQuery('#sizes_ddl');
            target.empty();
            jQuery(result).each(function () {
                jQuery(document.createElement('option'))
                    .attr("value", this.Value)
                    .text(this.Text)
                    .appendTo(target);
            });
        });
    };
    $(document).ready(function () {
        onShippingAccountIdChange($('#s_ddl'));
    });
</script>