SinExWebApp20328800/Models/ServicePackageFee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace SinExWebApp20328800.Models
{
    [Table("ServicePackageFee")]
    public class ServicePackageFee
    {

        public virtual int ServicePackageFeeID { get; set; }
        [Display(Name = "Fee")]
        public virtual decimal Fee { get; set; }
        [Display(Name = "Minimum Fee")]
    
        public virtual decimal MinimumFee { get; set; }
        [Display(Name = "Package Type")]

        public virtual int PackageTypeID { get; set; }
        [Display(Name = "Service Type")]

        public virtual int ServiceTypeID { get; set; }
        //
        public virtual PackageType PackageType { get; set; }
        public virtual ServiceType ServiceType { get; set; }

    }
}

SinExWebApp20328800/ViewModels/ServicePackageFeesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SinExWebApp20328800.Models;
using SinExWebApp20328800.ViewModels;
using System.Web.Mvc;

namespace SinExWebApp20328800.ViewModels
{
    public class ServicePackageFeesViewModel
    {
        public virtual IEnumerable<ServicePackageFee> Fees { get; set; }
        public virtual decimal Rate { get; set; }
        public virtual string CurrencyCode { get; set; }
        public virtual List<string> ServiceTypes { get; set; }
        public virtual List<string> PackageTypes { get; set; }
    }
}

SinExWebApp20328800/Controllers/ServicePackageFeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SinExWebApp20328800.Models;
using SinExWebApp20328800.ViewModels;

namespace SinExWebApp20328800.Controllers
{
    public class ServicePackageFeesController : Controller
    {
        private SinExWebApp20328800DatabaseContext db = new SinExWebApp20328800DatabaseContext();

        // GET: ServicePackageFees
        public ActionResult Index2()
        {
            ViewBag.penalty = db.Penalties.FirstOrDefault().PenaltyCharge;
            var servicePackageFees = db.ServicePackageFees.Include(s => s.PackageType).Include(s => s.ServiceType);
            return View(servicePackageFees.ToList());
        }

        // GET: ServicePackageFees
        public ActionResult Index(
            string CurrencyCode
            )
        {
            ServicePackageFeesViewModel servicePackageFeesViewModel = new ServicePackageFeesViewModel();

            var currencies = db.Currencies.ToList();
            servicePackageFeesViewModel.Fees = db.ServicePackageFees.Include(s => s.PackageType).Include(s => s.ServiceType);
            //set table Sheader data
            var ServiceTypes = db.ServiceTypes.Select(a => a).Distinct();
            servicePackageFeesViewModel.ServiceTypes = new List<string>();
            foreach (ServiceType item in ServiceTypes)
            {
                servicePackageFeesViewModel.ServiceTypes.Add(item.Type);
            }
            var PackageTypes = db.PackageTypes.Select(a => a).Distinct();
            servicePackageFeesViewModel.PackageTypes = new List<string>();
            foreach (PackageType item in PackageTypes)
            {
                servicePackageFeesViewModel.PackageTypes.Add(item.Type);
            }

            if (String.IsNullOrEmpty(CurrencyCode))
            {
                CurrencyCode = "CNY";
            }
            servicePackageFeesViewModel.Rate = currencies.SingleOrDefault(a => a.CurrencyCode == CurrencyCode).ExchangeRate;
            servicePackageFeesViewModel.CurrencyCode = CurrencyCode;

            ViewBag.currentCurrencyCode = CurrencyCode;
            foreach (ServicePackageFee fee in servicePackageFeesViewModel.Fees)
            {
                fee.Fee *= servicePackageFeesViewModel.Rate;
                fee.MinimumFee *= servicePackageFeesViewModel.Rate;
            }


            return View(servicePackageFeesViewModel);
        }

        // GET: ServicePackageFees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServicePackageFee servicePackageFee = db.ServicePackageFees.Find(id);
            if (servicePackageFee == null)
            {
                return HttpNotFound();
            }
            return View(servicePackageFee);
        }

        // GET: ServicePackageFees/Create
        public ActionResult Create()
        {
            ViewBag.PackageTypeID = new SelectList(db.PackageTypes, "PackageTypeID", "Type");
            ViewBag.ServiceTypeID = new SelectList(db.ServiceTypes, "ServiceTypeID", "Type");
            return View();
        }

        // POST: ServicePackageFees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ServicePackageFeeID,Fee,MinimumFee,PackageTypeID,ServiceTypeID")] ServicePackageFee servicePackageFee)
        {
            if (ModelState.IsValid)
            {
                db.ServicePackageFees.Add(servicePackageFee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PackageTypeID = new SelectList(db.PackageTypes, "PackageTypeID", "Type", servicePackageFee.PackageTypeID);
            ViewBag.ServiceTypeID = new SelectList(db.ServiceTypes, "ServiceTypeID", "Type", servicePackageFee.ServiceTypeID);
            return View(servicePackageFee);
        }

        // GET: ServicePackageFees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServicePackageFee servicePackageFee = db.ServicePackageFees.Find(id);
            if (servicePackageFee == null)
            {
                return HttpNotFound();
            }
            ViewBag.PackageTypeID = new SelectList(db.PackageTypes, "PackageTypeID", "Type", servicePackageFee.PackageTypeID);
            ViewBag.ServiceTypeID = new SelectList(db.ServiceTypes, "ServiceTypeID", "Type", servicePackageFee.ServiceTypeID);
            return View(servicePackageFee);
        }

        // POST: ServicePackageFees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ServicePackageFeeID,Fee,MinimumFee,PackageTypeID,ServiceTypeID")] ServicePackageFee servicePackageFee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(servicePackageFee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index2");
            }
            ViewBag.PackageTypeID = new SelectList(db.PackageTypes, "PackageTypeID", "Type", servicePackageFee.PackageTypeID);
            ViewBag.ServiceTypeID = new SelectList(db.ServiceTypes, "ServiceTypeID", "Type", servicePackageFee.ServiceTypeID);
            return View(servicePackageFee);
        }

        // GET: ServicePackageFees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServicePackageFee servicePackageFee = db.ServicePackageFees.Find(id);
            if (servicePackageFee == null)
            {
                return HttpNotFound();
            }
            return View(servicePackageFee);
        }

        // POST: ServicePackageFees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServicePackageFee servicePackageFee = db.ServicePackageFees.Find(id);
            db.ServicePackageFees.Remove(servicePackageFee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SinExWebApp20328800/Views/ServicePackageFees/Create.cshtml
@model SinExWebApp20328800.Models.ServicePackageFee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ServicePackageFee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Fee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinimumFee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinimumFee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinimumFee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PackageTypeID, "PackageTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PackageTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PackageTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceTypeID, "ServiceTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ServiceTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SinExWebApp20328800/Views/ServicePackageFees/Delete.cshtml
@model SinExWebApp20328800.Models.ServicePackageFee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ServicePackageFee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PackageType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PackageType.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceType.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinimumFee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinimumFee)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SinExWebApp20328800/Views/ServicePackageFees/Details.cshtml
@model SinExWebApp20328800.Models.ServicePackageFee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ServicePackageFee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PackageType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PackageType.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceType.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinimumFee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinimumFee)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ServicePackageFeeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SinExWebApp20328800/Views/ServicePackageFees/Edit.cshtml
@model SinExWebApp20328800.Models.ServicePackageFee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ServicePackageFee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ServicePackageFeeID)

        <div class="form-group">
            @Html.LabelFor(model => model.Fee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinimumFee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinimumFee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinimumFee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PackageTypeID, "PackageTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PackageTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PackageTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceTypeID, "ServiceTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ServiceTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SinExWebApp20328800/Views/ServicePackageFees/Index.cshtml
@model SinExWebApp20328800.ViewModels.ServicePackageFeesViewModel

@{
    ViewBag.Title = "Service/Package Fees";
}

<h2>Service/Package Fees</h2>
<hr />

@using (Html.BeginForm("index", "ServicePackageFees", FormMethod.Get))
{
    <div class="form-group">
        <div class="col-md-7">
            @Html.DropDownListFor(a => a.CurrencyCode, new SelectList(new List<string> { "CNY", "HKD", "TWD", "MOP" }).ToList(), new { @Value = ViewBag.currentCurrencyCode })
            <input type="submit" value="Change Currency" />
        </div>
    </div>
}

<h3>Currency: @Model.CurrencyCode &nbsp; &nbsp; &nbsp; Rate: @Model.Rate</h3>
<table class="table">
    <tr>
        <td></td>
        <th colspan="5">
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            Package Types
        </th>
    </tr>
    <tr>
        <th>
            Service Type
        </th>
        <td colspan="5"></td>
    </tr>
    <tr>
        <th></th>
        @foreach (string pt in Model.PackageTypes)
        {
            <th>
                @pt
            </th>
        }
    </tr>
    @foreach (string st in Model.ServiceTypes)
    {
        <tr>
            <td>
                @st
            </td>
            @foreach (string pt in Model.PackageTypes)
            {
                <td>
                    @foreach (var item in Model.Fees)
                    {
                        if (item.ServiceType.Type == st && item.PackageType.Type == pt)
                        {
                            @Html.DisplayFor(modelItem => item.Fee)
                            if (item.PackageType.Type != "Envelope")
                            {
                                 <text>/kg ( </text>@Html.DisplayFor(modelItem => item.MinimumFee)<text> min. )</text>
                            }
                        }
                    }
                </td>
            }
        </tr>
    }
</table>

<p>
    Warnimg: If a package's weight exceed the weight limit for the specific package type, a penalty charge will be applied to it.
</p>

SinExWebApp20328800/Views/ServicePackageFees/Index2.cshtml
@model IEnumerable<SinExWebApp20328800.Models.ServicePackageFee>

@{
    ViewBag.Title = "Change Fee";
}
<h2>Change Penalty Fee</h2>
<table class="table">
    <tr>
        <td>
            CNY @ViewBag.penalty
        </td>
        <td>
            @Html.ActionLink("Click here to modify penalty fee", "../Penalties/Edit/1")
        </td>
    </tr>
    <tr>
        <td>
        </td>
        <td>
        </td>
    </tr>
</table>


<h2>Change Service Package Fees</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PackageType.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServiceType.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MinimumFee)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PackageType.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceType.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MinimumFee)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ServicePackageFeeID })
            </td>
        </tr>

    }

</table>