SinExWebApp20328800/Controllers/CalculateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SinExWebApp20328800.Models;
using SinExWebApp20328800.ViewModels;

namespace SinExWebApp20328800.Controllers
{
    public class CalculateController : Controller
    {

        private SinExWebApp20328800DatabaseContext db = new SinExWebApp20328800DatabaseContext();
        // GET: Calculate
        public ActionResult Index()
        {
            FeeCalculateViewModel Calculator = new FeeCalculateViewModel();
            Calculator.param = new FeeCalculateSearchViewModel();
            //populate dropdownlists
            Calculator.param.origins = PopulateCitiesDropdownlist().ToList();
            Calculator.param.destinations = PopulateCitiesDropdownlist().ToList();
            Calculator.param.packageTypes = PopulatePackageTypesDropdownlist().ToList();
            Calculator.param.serviceTypes = PopulateServiceTypesDropdownlist().ToList();
            Calculator.param.currencies = PopulateCurrenciesDropdownlist().ToList();
            Calculator.param.sizes = new List<SelectListItem>();
            Calculator.packages = new List<FeeCalculatePackageViewModel>();
            Calculator.packages.Add(new FeeCalculatePackageViewModel());
            //populate size dropdownlist

            Calculator.param.sizes = new List<SelectListItem>();
            /*
            //set viewbag
            ViewBag.currentOrigin = origin;
            ViewBag.currentDestination = destination;
            ViewBag.currentServiceType = serviceType;
            ViewBag.currentCurrencyCode = currencyCode;
            //calculate result
            if (packageType != null && serviceType != null && weight != null && currencyCode != null)
            {
                Calculator.result = db.ServicePackageFees.SingleOrDefault(a => a.PackageType.Type == packageType && a.ServiceType.Type== serviceType);
                decimal price = 0 ;
                ViewBag.penalty = false;
                switch (Calculator.result.PackageTypeID)
                {
                    //Envelope
                    case 1:
                        price = Calculator.result.Fee;
                        break;
                    //Pak or Box
                    case 2:    
                    case 4:
                        int limit=0;
                        string limitString = db.PackageTypeSizes.Where(a => a.TypeSize == size).Select(a => a).First().WeightLimit;
                        bool convertResult = Int32.TryParse(limitString.Substring(0, limitString.Length-2), out limit);
                        ViewBag.limit = limit;
                        price = weight * Calculator.result.Fee > Calculator.result.MinimumFee ? (decimal)weight * Calculator.result.Fee : Calculator.result.MinimumFee;
                        if (limit!=0 && convertResult ==true && weight > (decimal)limit)
                        {
                            price += 500;
                            ViewBag.penalty = true;
                        }
                        //TODO: weight limit for box
                        break;
                    //Tube
                    case 3:
                        price = weight * Calculator.result.Fee > Calculator.result.MinimumFee ? (decimal)weight * Calculator.result.Fee : Calculator.result.MinimumFee;
                        break;
                    //Customer
                    case 5:
                        price = weight * Calculator.result.Fee > Calculator.result.MinimumFee ? (decimal)weight * Calculator.result.Fee : Calculator.result.MinimumFee;
                        break;
                }
                decimal rate = db.Currencies.Where(a => a.CurrencyCode == currencyCode).Select(a=>a.ExchangeRate).First();
                ViewBag.price = (price *rate).ToString("0.00");
                ViewBag.currency = currencyCode;
                ViewBag.weight = weight;
            }
            */
            return View(Calculator);
        }

        // POST: Currencies/Index
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "packages,origin,destination,serviceType,currencyCode,param")] FeeCalculateViewModel Calculator)
        {
            if (ModelState.IsValid)
            {
                decimal rate = db.Currencies.Where(a => a.CurrencyCode == Calculator.currencyCode).Select(a => a.ExchangeRate).First();
                foreach (FeeCalculatePackageViewModel package in Calculator.packages)
                {
                    string limitString = db.PackageTypeSizes.Where(a => a.TypeSize == package.size).Select(a => a).First().WeightLimit;
                    package.limit = limitString;
                    package.weight = Math.Round((decimal)package.weight, 1);
                    package.result = db.ServicePackageFees.SingleOrDefault(a => a.PackageType.Type == package.packageType && a.ServiceType.Type == Calculator.serviceType);
                    decimal price = 0;
                    package.penalty = false;
                    switch (package.result.PackageTypeID)
                    {
                        //Envelope
                        case 1:
                            price = package.result.Fee;
                            break;
                        //Pak or Box
                        case 2:
                        case 4:
                            price = package.weight * package.result.Fee > package.result.MinimumFee ? (decimal)package.weight * package.result.Fee : package.result.MinimumFee;
                            // weight limit
                            int limit = 0;
                            bool convertResult = Int32.TryParse(limitString.Substring(0, limitString.Length - 2), out limit);
                            if (limit != 0 && convertResult == true && package.weight > (decimal)limit)
                            {
                                price += db.Penalties.FirstOrDefault().PenaltyCharge;
                                package.penalty = true;
                            }
                            break;
                        //Tube
                        case 3:
                            price = package.weight * package.result.Fee > package.result.MinimumFee ? (decimal)package.weight * package.result.Fee : package.result.MinimumFee;
                            break;
                        //Customer
                        case 5:
                            price = package.weight * package.result.Fee > package.result.MinimumFee ? (decimal)package.weight * package.result.Fee : package.result.MinimumFee;
                            break;
                    }
                    package.fee = price * rate;
                }
                return View("Result", Calculator);
            }

            Calculator.param = new FeeCalculateSearchViewModel();
            //populate dropdownlists
            Calculator.param.origins = PopulateCitiesDropdownlist().ToList();
            Calculator.param.destinations = PopulateCitiesDropdownlist().ToList();
            Calculator.param.packageTypes = PopulatePackageTypesDropdownlist().ToList();
            Calculator.param.serviceTypes = PopulateServiceTypesDropdownlist().ToList();
            Calculator.param.currencies = PopulateCurrenciesDropdownlist().ToList();
            Calculator.param.sizes = new List<SelectListItem>();

            return View("Index", Calculator);
        }

        private SelectList PopulateCitiesDropdownlist()
        {
            var Query = db.Destinations.Select(a => a.City).Distinct().OrderBy(a => a);
            return new SelectList(Query);
        }

        private SelectList PopulatePackageTypesDropdownlist()
        {
            var Query = db.PackageTypes.Select(a => a.Type).Distinct().OrderBy(a => a);
            return new SelectList(Query);
        }

        private SelectList PopulateServiceTypesDropdownlist()
        {
            var Query = db.ServiceTypes.Select(a => a.Type).Distinct().OrderBy(a => a);
            return new SelectList(Query);
        }

        private SelectList PopulatePackageTypeSizesDropdownlist(string packageType)
        {
            var Query = db.PackageTypeSizes.Where(a => a.PackageType.Type == packageType).Select(a => a.TypeSize);
            return new SelectList(Query);
        }

        private SelectList PopulateCurrenciesDropdownlist()
        {
            var Query = db.Currencies.Select(a => a.CurrencyCode).Distinct().OrderBy(a => a);
            return new SelectList(Query);
        }

        public ActionResult GetSizes(string packageType)
        {
            if (String.IsNullOrEmpty(packageType))
            {
                return Json(new List<SelectListItem>(), JsonRequestBehavior.AllowGet);
            }

            var query = db.PackageTypeSizes.Where(a => a.PackageType.Type == packageType).Select(a => a.TypeSize);
            List<SelectListItem> data = new SelectList(query).ToList();

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetSizesByID(int? packageTypeID)
        {
            if (packageTypeID == null)
            {
                return Json(new List<SelectListItem>(), JsonRequestBehavior.AllowGet);
            }

            var query = db.PackageTypeSizes.Where(a => a.PackageType.PackageTypeID == packageTypeID);
            List<SelectListItem> data = new SelectList(query, "PackageTypeSizeID", "TypeSize").ToList();

            return Json(data, JsonRequestBehavior.AllowGet);
        }

    }
}

SinExWebApp20328800/Views/Calculate/Index.cshtml
@model SinExWebApp20328800.ViewModels.FeeCalculateViewModel

@{
    ViewBag.Title = "Fee Calculator";
}

<h2>Fee Calculator</h2>
<hr />

@using (Html.BeginForm("Index", "Calculate", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">

        <div class="col-md-12">
            <h3>Shipment</h3>
            <hr />
            @Html.LabelFor(a => a.serviceType, "Service Type: ", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownListFor(a => a.serviceType, Model.param.serviceTypes, "Please select...", new { @class = "form-control", Value = ViewBag.currentServiceType })
                @Html.ValidationMessageFor(a => a.serviceType, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(a => a.currencyCode, "Currency: ", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownListFor(a => a.currencyCode, Model.param.currencies, "Please select...", new { @class = "form-control", Value = ViewBag.currentCurrencyCode })
                @Html.ValidationMessageFor(a => a.currencyCode, "", new { @class = "text-danger" })
            </div>

            <div>

            </div>
            <h3>Packsges</h3>
            <hr />
            <div id="packageList">
                @for (int i = 0; i < Model.packages.Count; i++)
                {
                    <div class="packageRow col-md-12">

                        @Html.LabelFor(a => a.packages[i].packageType, "Package Type: ", new { @class = "control-label col-md-1" })
                        <div class="col-md-2">
                            @Html.DropDownListFor(a => a.packages[i].packageType, Model.param.packageTypes, "Please select...", new { @class = "form-control", Value = ViewBag.currentPackageType, id = "packageTypes_ddl", onchange = "+OnPackageTypesChange(this)", about = i })
                            @Html.ValidationMessageFor(a => a.packages[i].packageType, "", new { @class = "text-danger" })
                        </div>

                        @Html.LabelFor(a => a.packages[i].size, "Size: ", new { @class = "control-label col-md-1" })
                        <div class="col-md-2">
                            <select class="form-control" id="sizes_ddl_@i" name="packages[@i].size">
                                @foreach (SelectListItem item in Model.param.sizes)
                                {
                                    <option value="@item.Value">@item.Text</option>
                                }
                            </select>
                            @Html.ValidationMessageFor(a => a.packages[i].size, "", new { @class = "text-danger" })
                        </div>

                        @Html.LabelFor(a => a.packages[i].weight, "Weight(kg): ", new { @class = "control-label col-md-1", name =@i })
                        <div class="col-md-2" name="packages[@i].weight.div">
                            @Html.EditorFor(a => a.packages[i].weight, new { htmlAttributes = new { @class = "form-control", Value = ViewBag.currentWeight, id="weight" } })
                            @Html.ValidationMessageFor(a => a.packages[i].weight, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-md-3">
                            <i class="fa fa-2x fa-minus-circle remRow" style="color:red" aria-hidden="true"></i>
                        </div>
                    </div>
                }
            </div>


            <p>
                <i class="fa fa-2x fa-plus-circle addRow" style="color:deepskyblue" aria-hidden="true">Add package</i>
            </p>

        </div>
        <input class="btn btn-primary" type="submit" value="Calculate" />
    </div>
}
<script src="https://use.fontawesome.com/6e23d44a77.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" language="javascript">
    $(document).ready(function () {

        $(".addRow").click(function () {
            var rowCount = $('.packageRow').length;
            if (rowCount < 10) {
                $("#packageList").append('<div class="packageRow col-md-12"><label class="control-label col-md-1">Package Type: </label><div class="col-md-2"><select class="form-control" id="packageTypes_ddl" name="packages[' + rowCount + '].packageType" about="' + rowCount + '" onchange="+OnPackageTypesChange(this)"><option value="">Please select...</option>@foreach (SelectListItem item in Model.param.packageTypes){<option value="@item.Value">@item.Text</option>}</select><span class="field-validation-valid text-danger" data-valmsg-for="packages[' + rowCount + '].packageType" data-valmsg-replace="true"></span></div><label class="control-label col-md-1">Size: </label><div class="col-md-2"><select class="form-control" id="sizes_ddl_' + rowCount + '" name="packages[' + rowCount + '].size">@foreach (SelectListItem item in Model.param.sizes){<option value="@item.Value">@item.Text</option>}</select><span class="field-validation-valid text-danger" data-valmsg-for="packages[' + rowCount + '].size" data-valmsg-replace="true"></span></div><label class="control-label col-md-1" for="packages_' + rowCount + '__weight">Weight(kg): </label><div class="col-md-2" name="packages[' + rowCount + '].weight.div"><input  class="form-control text-box single-line" data-val="true" data-val-number="The field weight must be a number." data-val-required="The weight field is required." id="packages_' + rowCount + '__weight" name="packages[' + rowCount + '].weight" type="text"><span class="field-validation-valid text-danger" data-valmsg-for="packages[' + rowCount + '].weight" data-valmsg-replace="true"></span></div><div class="col-md-3"><i class="fa fa-2x fa-minus-circle remRow" style="color:red" aria-hidden="true"></i></div></div>');
            }
            else {
                alert('The maximum number of packages is 10.');
            }
        });

        $("#packageList").on('click', '.remRow', function () {

            $(this).closest('.packageRow').remove();

            $('.packageType').each(function (index) {
                $(this).attr('name', 'packages[' + index + '].packageType');
            });

            $('.packageSize').each(function (index) {
                $(this).attr('name', 'packages[' + index + '].size');
            });

            $('.packageWeight').each(function (index) {
                $(this).attr('name', 'packages[' + index + '].weight');
            });
        })
    });


    function AppendUrlParamTokens(url, params) {

        for (var param in params) {
            if (params[param] == null) {
                delete params[param];
            }
        }

        return url + "?" + jQuery.param(params);
    }

    function OnPackageTypesChange(ddl) {
        jQuery.getJSON(AppendUrlParamTokens('@Url.Action("GetSizes", "Calculate")', { packageType: ddl.options[ddl.selectedIndex].value }), function (result) {
            if (ddl.options[ddl.selectedIndex].value == "Envelope") {
                var destination = $("[name='packages[" + ddl.getAttribute('about') + "].weight.div']");
                destination.children(".text-box").val('0.0');
                $("[for='packages_" + ddl.getAttribute('about') + "__weight']").hide();
                destination.hide();
            } else {
                var destination = $("[name='packages[" + ddl.getAttribute('about') + "].weight.div']");
                $("[for='packages_" + ddl.getAttribute('about') + "__weight']").show();
                destination.show();
            }
            var id = "#sizes_ddl_" + ddl.getAttribute('about');
            var target = $(id);
            target.empty();
            jQuery(result).each(function () {
                jQuery(document.createElement('option'))
                    .text(this.Text)
                    .appendTo(target);
            });
        });
    };




</script>

SinExWebApp20328800/Views/Calculate/Result.cshtml
@model SinExWebApp20328800.ViewModels.FeeCalculateViewModel

@{
    ViewBag.Title = "Result";
}

<h2>Result</h2>
<div class="row">
    <div class="col-md-6 col-md-offset-2">
        <table class="table">
            <tr>
            <tr>
                <td>
                    Origin
                </td>
                <td>
                    @Model.origin
                </td>
            </tr>
            <tr>
                <td>
                    Destination
                </td>
                <td>
                    @Model.destination
                </td>
            </tr>
            <tr>
                <td>
                    Service Type
                </td>
                <td>
                    @Model.serviceType
                </td>
            </tr>
            <tr>
                <td>
                    Currency
                </td>
                <td>
                    @Model.currencyCode
                </td>
            </tr>

        </table>
    </div>

    <table class="table col-md-12">
        <tr>
            <th>
                Package Type
            </th>
            <th>
                Size
            </th>
            <th>
                Weight Limit
            </th>
            <th>
                Weight
            </th>
            <th>
                Package Fee
            </th>
        </tr>
        @foreach (var package in Model.packages)
        {
            <tr>
                <td>
                    @package.packageType
                </td>
                <td>
                    @package.size
                </td>
                <td>
                    Limit: @package.limit
                </td>
                <td>
                    @if (package.packageType == "Envelope")
                    {
                        <text>N/A</text>
                    }
                    else
                    {
                        @package.weight.ToString("F1")
                    }
                    
                </td>
                <td>
                    @Model.currencyCode &nbsp;@package.fee.ToString("F2") @if (package.penalty == true)
                    {
                        <div class="text-danger">(Including ¥500 penalty)</div>
                    }
                </td>

            </tr>
        }
        <tr>
            <td>
                <strong>
                    Total
                </strong>
            </td>
            <td></td>
            <td></td>
            <td>
                <strong>
                    @Model.packages.Sum(m => m.weight).ToString("F1") kg
                </strong>
            </td>
            <td>
                <strong>
                    @Model.currencyCode &nbsp;@Model.packages.Sum(m => m.fee).ToString("F2")
                </strong>
            </td>
        </tr>
    </table>
</div>
<p>
    @Html.ActionLink("Back", "Index")
</p>